// Code generated by protoc-gen-go. DO NOT EDIT.
// source: market.proto

package market

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Depth struct {
	Price                string   `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Depth) Reset()         { *m = Depth{} }
func (m *Depth) String() string { return proto.CompactTextString(m) }
func (*Depth) ProtoMessage()    {}
func (*Depth) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{0}
}

func (m *Depth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Depth.Unmarshal(m, b)
}
func (m *Depth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Depth.Marshal(b, m, deterministic)
}
func (m *Depth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Depth.Merge(m, src)
}
func (m *Depth) XXX_Size() int {
	return xxx_messageInfo_Depth.Size(m)
}
func (m *Depth) XXX_DiscardUnknown() {
	xxx_messageInfo_Depth.DiscardUnknown(m)
}

var xxx_messageInfo_Depth proto.InternalMessageInfo

func (m *Depth) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Depth) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type MarketResponse struct {
	Organize             string   `protobuf:"bytes,1,opt,name=organize,proto3" json:"organize,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BuyFirst             string   `protobuf:"bytes,3,opt,name=buy_first,json=buyFirst,proto3" json:"buy_first,omitempty"`
	SellFirst            string   `protobuf:"bytes,4,opt,name=sell_first,json=sellFirst,proto3" json:"sell_first,omitempty"`
	BuyDepth             []*Depth `protobuf:"bytes,5,rep,name=buy_depth,json=buyDepth,proto3" json:"buy_depth,omitempty"`
	SellDepth            []*Depth `protobuf:"bytes,6,rep,name=sell_depth,json=sellDepth,proto3" json:"sell_depth,omitempty"`
	Timestamp            int64    `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Temporize            int64    `protobuf:"varint,8,opt,name=Temporize,proto3" json:"Temporize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketResponse) Reset()         { *m = MarketResponse{} }
func (m *MarketResponse) String() string { return proto.CompactTextString(m) }
func (*MarketResponse) ProtoMessage()    {}
func (*MarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{1}
}

func (m *MarketResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketResponse.Unmarshal(m, b)
}
func (m *MarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketResponse.Marshal(b, m, deterministic)
}
func (m *MarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketResponse.Merge(m, src)
}
func (m *MarketResponse) XXX_Size() int {
	return xxx_messageInfo_MarketResponse.Size(m)
}
func (m *MarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarketResponse proto.InternalMessageInfo

func (m *MarketResponse) GetOrganize() string {
	if m != nil {
		return m.Organize
	}
	return ""
}

func (m *MarketResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MarketResponse) GetBuyFirst() string {
	if m != nil {
		return m.BuyFirst
	}
	return ""
}

func (m *MarketResponse) GetSellFirst() string {
	if m != nil {
		return m.SellFirst
	}
	return ""
}

func (m *MarketResponse) GetBuyDepth() []*Depth {
	if m != nil {
		return m.BuyDepth
	}
	return nil
}

func (m *MarketResponse) GetSellDepth() []*Depth {
	if m != nil {
		return m.SellDepth
	}
	return nil
}

func (m *MarketResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MarketResponse) GetTemporize() int64 {
	if m != nil {
		return m.Temporize
	}
	return 0
}

type MarketRequest struct {
	Organize             string   `protobuf:"bytes,1,opt,name=organize,proto3" json:"organize,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Keys                 []string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketRequest) Reset()         { *m = MarketRequest{} }
func (m *MarketRequest) String() string { return proto.CompactTextString(m) }
func (*MarketRequest) ProtoMessage()    {}
func (*MarketRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f90997f23a2c3f8, []int{2}
}

func (m *MarketRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketRequest.Unmarshal(m, b)
}
func (m *MarketRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketRequest.Marshal(b, m, deterministic)
}
func (m *MarketRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketRequest.Merge(m, src)
}
func (m *MarketRequest) XXX_Size() int {
	return xxx_messageInfo_MarketRequest.Size(m)
}
func (m *MarketRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketRequest proto.InternalMessageInfo

func (m *MarketRequest) GetOrganize() string {
	if m != nil {
		return m.Organize
	}
	return ""
}

func (m *MarketRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MarketRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*Depth)(nil), "market.Depth")
	proto.RegisterType((*MarketResponse)(nil), "market.MarketResponse")
	proto.RegisterType((*MarketRequest)(nil), "market.MarketRequest")
}

func init() {
	proto.RegisterFile("market.proto", fileDescriptor_3f90997f23a2c3f8)
}

var fileDescriptor_3f90997f23a2c3f8 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xff, 0x36, 0x6d, 0xfe, 0xf8, 0x42, 0x19, 0x2c, 0xa8, 0xac, 0x02, 0x52, 0x94, 0x29,
	0x42, 0xa8, 0x43, 0x11, 0x1b, 0x13, 0x42, 0x65, 0x62, 0x89, 0x90, 0x90, 0x58, 0x50, 0x02, 0x06,
	0xa2, 0xc6, 0xb1, 0xb1, 0x9d, 0x21, 0x3c, 0x08, 0xcf, 0x8b, 0xec, 0xeb, 0x14, 0x81, 0x98, 0xd8,
	0x72, 0xce, 0xb9, 0xfe, 0x92, 0xe3, 0x1b, 0xd8, 0x15, 0xa5, 0xde, 0x70, 0xbb, 0x54, 0x5a, 0x5a,
	0x49, 0x63, 0x54, 0xd9, 0x39, 0x4c, 0xaf, 0xb8, 0xb2, 0xaf, 0x74, 0x1f, 0xa6, 0x4a, 0xd7, 0x8f,
	0x9c, 0x8d, 0xd2, 0x51, 0x4e, 0x0a, 0x14, 0x74, 0x0e, 0x71, 0x29, 0x64, 0xd7, 0x5a, 0x36, 0xf6,
	0x76, 0x50, 0xd9, 0xc7, 0x18, 0xf6, 0x6e, 0x3c, 0xa1, 0xe0, 0x46, 0xc9, 0xd6, 0x70, 0xba, 0x80,
	0x44, 0xea, 0x97, 0xb2, 0xad, 0xdf, 0x07, 0xc6, 0x56, 0x3b, 0x8c, 0xe9, 0x45, 0x25, 0x9b, 0x01,
	0x83, 0x8a, 0x1e, 0x02, 0xa9, 0xba, 0xfe, 0xe1, 0xb9, 0xd6, 0xc6, 0xb2, 0x08, 0x0f, 0x55, 0x5d,
	0xbf, 0x76, 0x9a, 0x1e, 0x03, 0x18, 0xde, 0x34, 0x21, 0x9d, 0xf8, 0x94, 0x38, 0x07, 0xe3, 0x13,
	0x3c, 0xfb, 0xe4, 0xbe, 0x9e, 0x4d, 0xd3, 0x28, 0xdf, 0x59, 0xcd, 0x96, 0xa1, 0xa3, 0xaf, 0xe4,
	0x51, 0x58, 0xee, 0x34, 0xa0, 0x70, 0x38, 0xfe, 0x6d, 0xd8, 0x93, 0x71, 0xfa, 0x08, 0x88, 0xad,
	0x05, 0x37, 0xb6, 0x14, 0x8a, 0xfd, 0x4f, 0x47, 0x79, 0x54, 0x7c, 0x19, 0x2e, 0xbd, 0xe5, 0x42,
	0x49, 0xed, 0x8a, 0x26, 0x98, 0x6e, 0x8d, 0xec, 0x0e, 0x66, 0xc3, 0xbd, 0xbc, 0x75, 0xdc, 0xd8,
	0x3f, 0x5d, 0x0b, 0x85, 0xc9, 0x86, 0xf7, 0x86, 0x45, 0x69, 0x94, 0x93, 0xc2, 0x3f, 0xaf, 0xd6,
	0x10, 0x23, 0x98, 0x5e, 0x00, 0xb9, 0xe6, 0x36, 0x88, 0x83, 0xa1, 0xc5, 0xb7, 0xb7, 0x2e, 0xe6,
	0x3f, 0x6d, 0x5c, 0x52, 0xf6, 0xef, 0x32, 0xb9, 0x0f, 0xab, 0xaf, 0x62, 0xff, 0x27, 0x9c, 0x7d,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x8d, 0x50, 0xfa, 0x19, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MarketClient is the client API for Market service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MarketClient interface {
	GetMarket(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error)
}

type marketClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketClient(cc grpc.ClientConnInterface) MarketClient {
	return &marketClient{cc}
}

func (c *marketClient) GetMarket(ctx context.Context, in *MarketRequest, opts ...grpc.CallOption) (*MarketResponse, error) {
	out := new(MarketResponse)
	err := c.cc.Invoke(ctx, "/market.Market/GetMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketServer is the server API for Market service.
type MarketServer interface {
	GetMarket(context.Context, *MarketRequest) (*MarketResponse, error)
}

// UnimplementedMarketServer can be embedded to have forward compatible implementations.
type UnimplementedMarketServer struct {
}

func (*UnimplementedMarketServer) GetMarket(ctx context.Context, req *MarketRequest) (*MarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarket not implemented")
}

func RegisterMarketServer(s *grpc.Server, srv MarketServer) {
	s.RegisterService(&_Market_serviceDesc, srv)
}

func _Market_GetMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketServer).GetMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/market.Market/GetMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketServer).GetMarket(ctx, req.(*MarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Market_serviceDesc = grpc.ServiceDesc{
	ServiceName: "market.Market",
	HandlerType: (*MarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarket",
			Handler:    _Market_GetMarket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "market.proto",
}
